{
 "title": "go-svc",
 "tags": [ "go-svc" ],
 "time": { "from": "now-12h", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "default" },
   { "name": "container", "query": "go-svc" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version info",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "version_info { namespace=\"$namespace\", container=\"$container\" }"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "description": "Total number of requests in selected time range.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    increase(http_server_requests_seconds_count{ namespace=\"$namespace\", container=\"$container\" }[$__range])\n)"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "stat",
   "description": "Total number of requests per second.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{ namespace=\"$namespace\", container=\"$container\" }[$__range]))"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "stat",
   "description": "Request latency in 50th quantile.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket { namespace=~\"$namespace\", container=\"$container\" }[$__range])) by (le))"
    }
   ]
  },
  {
   "title": "4xx errors",
   "type": "stat",
   "description": "Number of requests with a client error code 4xx in the selected time range.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_requests_seconds_count{ namespace=~\"$namespace\", container=\"$container\", code=~\"4[0-9]{2}\" }[$__range])))"
    }
   ]
  },
  {
   "title": "5xx errors",
   "type": "stat",
   "description": "Number of requests with a server error code 5xx in the selected time range.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(http_server_requests_seconds_count{ namespace=~\"$namespace\", container=\"$container\", code=~\"5[0-9]{2}\" }[$__range])))"
    }
   ]
  },
  {
   "title": "Response Time (avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (url) (\n  rate(http_server_requests_seconds_sum { namespace=\"$namespace\", container=\"$container\" }[$__rate_interval])\n) / \nsum by (url) (\n  rate(http_server_requests_seconds_count { namespace=\"$namespace\", container=\"$container\" }[$__rate_interval])\n)",
     "legendFormat": "{{url}}"
    },
    {
     "expr": "max by (url) (http_server_requests_seconds_max{ namespace=\"$namespace\", container=\"$container\" })",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Traffic increase",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(http_server_requests_seconds_count { namespace=\"$namespace\", container=\"$container\", code!~\"5[0-9]{2}\" }[$__rate_interval])\n)",
     "legendFormat": "{{uri}}"
    },
    {
     "expr": "sum (\n  rate(http_server_requests_seconds_count{ namespace=\"$namespace\", container=\"$container\", code!~\"5[0-9]{2}\" }[$__rate_interval] offset 1d)\n)",
     "legendFormat": "{{uri}} [D-1]"
    },
    {
     "expr": "sum (\n  rate(http_server_requests_seconds_count{ namespace=\"$namespace\", container=\"$container\", code!~\"5[0-9]{2}\" }[$__rate_interval] offset 7d)\n)",
     "legendFormat": "{{uri}} [D-7]"
    }
   ]
  },
  {
   "title": "Error Rate (5xx)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (\n  rate(http_server_requests_seconds_count{ namespace=\"$namespace\", container=\"$container\", code=~\"5[0-9]{2}\" }[$__rate_interval])\n)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  { "title": "Traffic by endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (url, method) (\n  rate(http_server_requests_seconds_count { namespace=\"$namespace\", container=\"$container\"}[$__rate_interval])\n)!=0",
     "legendFormat": "[{{method}}] {{url}}"
    }
   ]
  },
  {
   "title": "Traffic distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (url, method) (\n  increase(http_server_requests_seconds_count { namespace=\"$namespace\", container=\"$container\"}[$__range])\n)!=0",
     "legendFormat": "[{{method}}] {{url}}"
    }
   ]
  },
  {
   "title": "Goroutine stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{ namespace=\"$namespace\", container=\"$container\" }",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "OS Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_threads{ namespace=\"$namespace\", container=\"$container\" }",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_open_fds{ namespace=\"$namespace\", container=\"$container\" }",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "alloc bytes allocated",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{ namespace=\"$namespace\", container=\"$container\" }",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "stack in use - bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{ namespace=\"$namespace\", container=\"$container\" }",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "heap in use - bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{ namespace=\"$namespace\", container=\"$container\" }",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}