---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: go-svc

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - podmonitor.yaml

configMapGenerator:
  - name: dashboard-go-svc
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
    files:
      - dashboards/go-svc.json
